services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ghostnet
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=ghostnet
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["node", "server.js"]
    
  ghostnet-dev:
    build: ./ghostnet-web
    volumes:
      - ./ghostnet-web/app:/app          # Mount local source code
      - /app/node_modules # Node modules persistent in container
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Hot reload op RPi
    stdin_open: true
    tty: true

# docker-compose build ghostnet-prod
#  ghostnet-prod:
#    build:
#      context: .
#      dockerfile: ~/GhostNet/docker/ghostnet-web/Dockerfile.prod
#    ports:
#      - "3001:3000"

  lora-handler:
    build: ./lora-handler
    container_name: lora_handler
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: ghostnet
      USB_PORT: /dev/ttyUSB0
      USB_BAUDRATE: 115200
      PYTHONUNBUFFERED: 1
    volumes:
      - ./lora-handler:/app
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  webserver:
    build: ./webserver
    container_name: GhostNetWeb
    depends_on:
      - mysql
    ports:
      - "8888:80"
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: ghostnet
    volumes:
      - ./webserver:/app
    restart: always

volumes:
  mysql_data:
